// <auto-generated />
namespace WP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Discussion_AddDateTimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Discussion_AddDateTimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201710090613500_Discussion_AddDateTimes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
